#!/bin/bash

while (true);
do cd /progs/amtcftp/error;
echo "Errors in error folder!!!"
ls -lt;
	if [[ $(ls /progs/amtcftp/error | wc -l | bc) != 0 ]];
		then for ((i=1;i<=6;i++));
			do echo -en "\a";
				usleep 500000; 
			done; 
	fi 2>/dev/null;
#sleep 10;
cd /progs/amtcftp/comsysPX/error;
echo -e ">>>Files in the comsys/error folder:"
Number=$(ls | wc -l);
echo -e "Number of error files: $Number"

CHECKFOLDER=/app/xib/ext/support/luis/NOTOUCH/COMSYSPX;
ERRORFOLDER=/progs/amtcftp/comsysPX/error;
RESENDFOLDER=/progs/amtcftp/comsysPX/resend;
HKFOLDER=/app/xib/ext/support/error/2019;


ls -lt | grep -v 'total';
	if [[ $(ls /progs/amtcftp/comsysPX/error | wc -l | bc) != 0 ]];
		then for ((i=1;i<=6;i++));
				do echo -en "\a";
				usleep 500000; 
			done; 
			echo -e ">>>Check if these files are resent or not:"
			for check in $(ls -1 $ERRORFOLDER);
				do 	Count=$(find $CHECKFOLDER -type f -name "$check"  | wc -l| bc)
					if [ $Count == 0 ];
							then echo 'This file is not resent,copy to backup folder and move to resend folder'; 
								 cp  $ERRORFOLDER/$check $CHECKFOLDER;
								 echo "cp"  $ERRORFOLDER/$check $CHECKFOLDER;
								 mv  $ERRORFOLDER/$check $RESENDFOLDER;
								 echo "mv"  $ERRORFOLDER/$check $RESENDFOLDER;
					elif [ $Count == 1 ];
							then 	month=$(date +%m);
									echo 'This file is already resent, directly housekeeping';
									mv  $ERRORFOLDER/$check $HKFOLDER/$month;
									echo "mv  $ERRORFOLDER/$check $HKFOLDER/$month";
					fi;
			done;
	fi;
#echo "ComsysPX resend finished!!!";
#sleep 10;
echo;
echo -e "Next, start to check the list2:"
/opt/amtcftp/tools/support/bin/list2 -runbycron | sed -n '/Customer directories (DOWNLOAD)/,/Customer directories (UPLOAD)/p' ;
cd $sup/luis;
sleep 300;
done;
