#!/bin/bash

while (true);
do cd /progs/amtcftp/error;
echo "Errors in error folder!!!"
ls -lt;
	if [[ $(ls /progs/amtcftp/error | wc -l | bc) != 0 ]];
		then for ((i=1;i<=6;i++));
			do echo -en "\a";
				usleep 500000; 
			done; 
	fi 2>/dev/null;
#sleep 10;
cd /progs/amtcftp/comsysPX/error;
echo "Resend files; /progs/amtcftp/comsysPX/resend/, if fail again, hk"

CHECKFOLDER=/app/xib/ext/support/luis/COMSYSPX;
ERRORFOLDER=/progs/amtcftp/comsysPX/error;
RESENDFOLDER=/progs/amtcftp/comsysPX/resend;
HKFOLDER=/app/xib/ext/support/error/2019;


ls -lt;
	if [[ $(ls /progs/amtcftp/comsysPX/error | wc -l | bc) != 0 ]];
		then for ((i=1;i<=6;i++));
				do echo -en "\a";
				usleep 500000; 
			done; 
			for check in $(ls -1 $ERRORFOLDER);
				do 	Count=$(find $CHECKFOLDER -type f -name "$check"  | wc -l| bc)
					if [ $Count == 0 ];
							then echo 'This files is not resent'; 
								 cp  $ERRORFOLDER/$check $CHECKFOLDER;
								 echo 'cp  $ERRORFOLDER/$check $CHECKFOLDER';
								 mv  $ERRORFOLDER/$check $RESENDFOLDER;
								 echo 'mv  $ERRORFOLDER/$check $RESENDFOLDER';
					elif [ $Count == 1 ];
							then 	month=$(date +%m);
									echo 'This file is already resent';
									mv  $ERRORFOLDER/$check $HKFOLDER/$month;
									echo 'mv  $ERRORFOLDER/$check $HKFOLDER/$month';
					fi;
			done;
	fi;
echo "ComsysPX resend finished!!!";
#sleep 10;
/opt/amtcftp/tools/support/bin/list2 -runbycron | sed -n '/Customer directories (DOWNLOAD)/,/Customer directories (UPLOAD)/p' ;
cd $sup/luis;
sleep 300;
done;
