#!/bin/bash

###########################################################
#Create this script to handle exp files automatically.
#2020.01.05
#
#
#
#2020.01.07	fixed Manually test and debug 
###########################################################

COM=/app/sword/schenker/comsys
imp_directory=`dirname ${COM}/COMS*/agr/*outbound/imp/$1`
agr_directory=${imp_directory%/*}

#echo the current pending file
echo -e ">>>pending file as below:"
echo -e "**********************************************************************************************************************"
echo -e `dirname ${COM}/COMS*/agr/*outbound/imp/$1`:
echo -e "**********************************************************************************************************************"
echo -e "$1"
echo -e "**********************************************************************************************************************"


#check the agreement parameters:
echo;echo -e ">>>the parameters as below:"
grep -E 'Protocol|RemoteHost|User|RemoteDir|Description' ${agr_directory}/*xml

#check the error log
echo;echo -e ">>>check the log and find the issue below:"
latest_protlog=`ls -t  ${agr_directory}/prot|head -1`
grep $1 ${agr_directory}/prot/${latest_protlog} | head -10
echo -e "......"




**********************************************************************************************************************
/app/sword/schenker/comsys/COMS1_06/agr/APPLEXDASH_outbound/imp:              1 file(s)
**********************************************************************************************************************
     oldest file: -rw-rw---- 1 comsys b2bi 224 Jan  6 21:40 APPLEXDASH_outbound.76204718.dbschenker_INDC_20200107020947.csv
**********************************************************************************************************************
